# Generated by Django 2.2.4 on 2019-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190901_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
            ],
        ),
    ]
