# Generated by Django 2.2.4 on 2019-09-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_house_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_house_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=100)),
                ('doing_quality', models.CharField(max_length=50)),
                ('ammont', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='house_details',
        ),
    ]
