# Generated by Django 2.2.4 on 2019-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190902_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_house_details',
            name='ammont',
        ),
        migrations.AddField(
            model_name='top_house_details',
            name='ammount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
