# Generated by Django 2.2.4 on 2019-09-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190902_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_house_details',
            name='company_name',
        ),
    ]
