# Generated by Django 2.2.4 on 2019-09-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_top_house_details_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_details',
            name='contruct_info',
            field=models.CharField(default='jahid', max_length=50),
        ),
    ]
