# Generated by Django 2.2.4 on 2019-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contract_details_contruct_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_details',
            name='Address',
            field=models.CharField(default='Address', max_length=50),
        ),
        migrations.AddField(
            model_name='contract_details',
            name='Address_details',
            field=models.CharField(default='203 Fake St. Mountain View, San Francisco, California, USA', max_length=100),
        ),
        migrations.AddField(
            model_name='contract_details',
            name='email_adress',
            field=models.CharField(default='programmerjahid162"gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='contract_details',
            name='phone',
            field=models.CharField(default='Phone', max_length=10),
        ),
        migrations.AddField(
            model_name='contract_details',
            name='phone_number',
            field=models.CharField(default='+1 232 3235 324', max_length=12),
        ),
        migrations.AlterField(
            model_name='contract_details',
            name='contruct_info',
            field=models.CharField(default='Contruct Info', max_length=50),
        ),
    ]
