# Generated by Django 2.2.4 on 2019-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190902_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_details',
            name='email_adress',
            field=models.CharField(default='programmerjahid162@gmail.com', max_length=50),
        ),
    ]
