# Generated by Django 2.2.4 on 2019-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190902_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_details',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contract_details',
            name='phone_num',
            field=models.CharField(default='01794895700', max_length=15),
        ),
    ]
