# Generated by Django 2.2.4 on 2019-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190902_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_details',
            name='our_agent_details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
