# Generated by Django 2.2.4 on 2019-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20190902_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='defualt_detials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_homeland', models.CharField(default='', max_length=50)),
                ('about_homeland_details', models.CharField(default='', max_length=150)),
                ('navigatons', models.CharField(default='', max_length=120)),
                ('flowus', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
