# Generated by Django 2.2.4 on 2019-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_defualt_detials'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_house_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=50)),
                ('house_location', models.CharField(max_length=50)),
                ('rent_price', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
                ('baths', models.CharField(max_length=50)),
                ('spaces', models.CharField(max_length=50)),
            ],
        ),
    ]
