# Generated by Django 2.2.4 on 2019-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_index_defoult_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_defoult_change',
            name='chose_details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
