# Generated by Django 2.2.4 on 2019-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20190903_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_details',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
