# Generated by Django 2.2.4 on 2019-09-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_about_page_defaut_ledership_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post_create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_blog_post', models.CharField(max_length=100)),
                ('blog_post_title', models.CharField(max_length=100)),
                ('blog_post_details', models.CharField(max_length=400)),
            ],
        ),
    ]
