# Generated by Django 2.2.4 on 2019-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_blog_post_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_details',
            name='fb_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agent_details',
            name='linkend_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agent_details',
            name='twitter_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
