# Generated by Django 2.2.4 on 2019-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20190905_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_details',
            name='company_name',
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
