# Generated by Django 2.2.4 on 2019-09-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20190905_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_house_details',
            name='offer_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
