# Generated by Django 2.2.4 on 2019-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_index_house_details_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='defualt_detials',
            name='fb_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='linkend_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='twitter_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
