# Generated by Django 2.2.4 on 2019-09-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20190909_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defualt_detials',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='defualt_detials',
            name='linkend_link',
        ),
        migrations.RemoveField(
            model_name='defualt_detials',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='company_fb_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='company_linkend_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='company_twitter_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
