# Generated by Django 2.2.4 on 2019-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20190909_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='defualt_detials',
            name='company_instagrame_link',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
