# Generated by Django 2.2.4 on 2019-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_defualt_detials_company_instagrame_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defualt_detials',
            name='flowus',
        ),
        migrations.RemoveField(
            model_name='defualt_detials',
            name='navigatons',
        ),
        migrations.AddField(
            model_name='defualt_detials',
            name='our_company_details',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
