# Generated by Django 2.2.4 on 2019-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20190909_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_page_defaut',
            name='ledershi_details',
        ),
        migrations.RemoveField(
            model_name='about_page_defaut',
            name='ledership_title',
        ),
        migrations.AddField(
            model_name='about_page_defaut',
            name='ledership_details',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
