# Generated by Django 2.2.4 on 2019-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20190909_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_house_details',
            name='house_image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
