# Generated by Django 2.2.4 on 2019-09-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20190910_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledership_details',
            name='leader_ship_agent_image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
