# Generated by Django 2.2.4 on 2019-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_ledership_details_leader_ship_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_details',
            name='our_angent_image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
